name: deploy-action
on:
  push:
    branches:
      - master
      - main
jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Merged to master/main successfully!'

      - name: Make ~/.ssh directory
        run: mkdir ~/.ssh

      - name: Adding SSH Key
        run: 'echo "SSH_PRIVATE_KEY" > ~/.ssh/id_rsa'
        env:
          SSH_KEY: ${{secrets.SSH_PRIVATE_KEY}}

      - name: Change SSH Key chmod
        run: chmod 400 ~/.ssh/id_rsa

      - name: Generate public key from private
        run: ssh-keygen -f ~/.ssh/id_rsa -y > ~/.ssh/id_rsa.pub

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

      - run: ssh -t masstermax@${{ secrets.SSH_HOST }} "cd ~/projects/image-to-code &&
          git checkout master &&
          git pull &&
          env BOT_API_TOKEN=${{ secrets.BOT_API_TOKEN }} bash run.sh"
