name: deploy-action
on:
  push:
    branches:
      - master
jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Merged to master successfully!'

      - name: Make ~/.ssh directory
        run: mkdir ~/.ssh

      - name: Adding SSH Key with chmod 400
        run: 'echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 400 ~/.ssh/id_rsa'
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

      - run: ssh -t masstermax@${{ secrets.SSH_HOST }} "cd ~/projects/image-to-code &&
          git checkout master &&
          git pull &&
          env BOT_API_TOKEN=${{ secrets.BOT_API_TOKEN }} bash run.sh"
