name: deploy-action
on:
  push:
    branches:
      - master
      - main
jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Merged to master/main successfully!'

      - name: Adding SSH Key
        run: echo ${{ secrets.SSH_PRIVATE_KEY }}  >> ~/.ssh/id_rsa

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

      - run: ssh -t masstermax@${{ secrets.SSH_HOST }} "cd ~/projects/image-to-code &&
          git checkout master &&
          git pull &&
          env BOT_API_TOKEN=${{ secrets.BOT_API_TOKEN }} bash run.sh"
