name: test-cov-action
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - name: "Checkout Repo"
      - uses: actions/checkout@v3

      - name: "Set up Python ${{ matrix.python-version }}"
      - uses: actions/setup-python@v1
        with:
          - python-version: ${{ matrix.python-version }}

      - name: "Install Dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt

      - name: "Lint"
        run: |
          pylint --jobs 1 --rcfile=setup.cfg src

      - name: "Download CodeT5Model"
        run: |
          wget --load-cookies /tmp/cookies.txt
          "https://docs.google.com/uc?export=download&confirm=$(wget
          --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies
          --no-check-certificate 'https://docs.google.com/uc?export=download&id=19Sb_aMCi-XIBrjqlDiGpYOwG7MmCpWnj'
          -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=19Sb_aMCi-XIBrjqlDiGpYOwG7MmCpWnj"
          -O /resources/model/codet5_model.bin && rm -rf /tmp/cookies.txt

      - name: "Run Tests with Coverage"
        run: pytest

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1